name:                haskellNyumonHandson3
version:             0.1.0.0
github:              "githubuser/haskellNyumonHandson3"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/haskellNyumonHandson3#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskellNyumonHandson3_0:
    main:                haskellNyumonHandson3_0.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-tabs
    dependencies:
    - haskellNyumonHandson3
    - xturtle-slide

  haskellNyumonHandson3_1:
    main:                haskellNyumonHandson3_1.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-tabs
    dependencies:
    - haskellNyumonHandson3
    - xturtle-slide

  haskellNyumonHandson3_2:
    main:                haskellNyumonHandson3_2.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-tabs
    dependencies:
    - haskellNyumonHandson3
    - xturtle-slide

  haskellNyumonHandson3_3:
    main:                haskellNyumonHandson3_3.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-tabs
    dependencies:
    - haskellNyumonHandson3
    - xturtle-slide

  haskellNyumonHandson3_4:
    main:                haskellNyumonHandson3_4.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-tabs
    dependencies:
    - haskellNyumonHandson3
    - xturtle-slide

  haskellNyumonHandson3_5:
    main:                haskellNyumonHandson3_5.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-tabs
    dependencies:
    - haskellNyumonHandson3
    - xturtle-slide

  haskellNyumonHandson3_6:
    main:                haskellNyumonHandson3_6.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-tabs
    dependencies:
    - haskellNyumonHandson3
    - xturtle-slide

tests:
  haskellNyumonHandson3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellNyumonHandson3
